[package]
name = "maxminddb"
version = "0.8.0"
description = "Library for reading MaxMind DB format used by GeoIP2"
documentation = "http://oschwald.github.io/maxminddb-rust/maxminddb/struct.Reader.html"
readme = "README.md"
keywords = ["MaxMind", "GeoIP2", "GeoIP", "geolocation", "ip"]
authors = [ "Gregory J. Oschwald <oschwald@gmail.com>" ]
homepage = "https://github.com/oschwald/maxminddb-rust"
repository = "https://github.com/oschwald/maxminddb-rust"
license = "ISC"

[lib]
name ="maxminddb"
crate_type = ["lib", "dylib", "staticlib"]
path = "src/maxminddb/lib.rs"

[dependencies]
log = "0.3.8"
serde = "1.0.8"
serde_derive = "1.0.8"

[dev-dependencies]
env_logger = "0.4"
