[package]
name = "maxminddb"
version = "0.6.2"
description = "Library for reading MaxMind DB format used by GeoIP2"
documentation = "http://oschwald.github.io/maxminddb-rust/maxminddb/struct.Reader.html"
readme = "README.md"
keywords = ["MaxMind", "GeoIP2", "GeoIP", "geolocation", "ip"]
authors = [ "Gregory J. Oschwald <oschwald@gmail.com>" ]
homepage = "https://github.com/oschwald/maxminddb-rust"
repository = "https://github.com/oschwald/maxminddb-rust"
license = "ISC"

[lib]
name ="maxminddb"
crate_type = ["lib", "dylib", "staticlib"]
path = "src/maxminddb/lib.rs"

[dependencies]
log = "0.3.5"
rustc-serialize = "0.3.16"
clippy = {version = "0.0.37", optional = true}

[features]
default = []
dev = ["clippy"]
