[package]

name = "maxminddb"
version = "0.1.8"
description = "Library for reading MaxMind DB format used by GeoIP2"
readme = "README.md"
keywords = ["MaxMind", "GeoIP2", "GeoIP", "geolocation"]
authors = [ "Gregory J. Oschwald <oschwald@gmail.com>" ]
homepage = "https://github.com/oschwald/maxminddb-golang"
license = "Apache-2.0"

[lib]

name ="maxminddb"
crate_type = ["lib", "dylib", "staticlib"]
path = "src/maxminddb/lib.rs"

[dependencies]

log = "0.2.5"
rustc-serialize = "0.3.0"
